steps:
  - label: "npm ci"
    commands: 
      - "source use-node 14"
      - "npm ci"
      - "tar -czf node_modules.tar node_modules"
    artifact_paths: "node_modules.tar"

  - wait

  - label: "Lint"
    commands:
      - "source use-node 14"
      - "buildkite-agent artifact download node_modules.tar ."
      - "tar -xzf node_modules.tar"
      - "npm run lint"

  - label: "Lighthouse CI"
    commands:
      - "source use-node 14"
      - "buildkite-agent artifact download node_modules.tar ."
      - "tar -xzf node_modules.tar"
      - "CI=false npm run build"
      - "npm install -g @lhci/cli@0.8.x"
      - "lhci autorun"

  - wait

  - label: "Release and bump version"
    commands:
      - "source use-node 14"
      - "buildkite-agent artifact download node_modules.tar . && tar -xzf node_modules.tar"
      - ".ci/release.sh"
    branches: "*.*"
