name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:	
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.FRONTEND_REPO_ACTIONS_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Frontend Project
    steps:
      - name: Assign NEW issues to the Frontend org-level project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/orgs/hackathon/projects/9'
